#!/bin/bash

#Private key
openssl genrsa -des3 -out certs/domain.key 1024
#CSR
openssl req -new -key certs/domain.key -out certs/domain.csr
#Remove Passphrase
cp certs/domain.key certs/domain.key.org
openssl rsa -in certs/domain.key.org -out certs/domain.key
#Generate self signed certificate
openssl x509 -req -days 365 -in certs/domain.csr -signkey certs/domain.key -out certs/domain.crt





chmod 400 host.key
cp host.cert cert/domain.crt 
cp host.key cert/domain.key
sudo mkdir -p /etc/docker/certs.d/docker-registry:5000
sudo cp certs/domain.crt /etc/docker/certs.d/docker-registry:5000/ca.crt
sudo systemctl restart docker

sudo docker run -d \
  -e REGISTRY_HTTP_ADDR=0.0.0.0:5000 \
  -p 5000:5000 \
  -v data:/var/lib/registry \
  -v "$(pwd)"/certs:/certs \
  -e REGISTRY_HTTP_ADDR=0.0.0.0:443 \
  -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt \
  -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key \
  -p 443:443 \
  --name custom-registry \
  registry:2
