pipeline {
    agent any

    environment {
        APP_DIR = 'utn-devops-app/myapp'
        DEFAULT_BRANCH = 'unidad-2'
    }

    stages {
        stage('Prepare') {
            steps {
                sh "git clone https://github.com/Fichen/utn-devops-app.git || true"
                sh "cd ${APP_DIR} && git checkout ${DEFAULT_BRANCH}"
                sh "cd ${APP_DIR} && sudo /usr/local/bin/composer install"
                sh "chmod 777 ${APP_DIR}/bootstrap/cache/"
            }
        }
        stage('Build') {
            steps {
                sh "find . -path ./${APP_DIR}/vendor -prune -o -name \\*.php -exec php -l \"{}\" \\;"
                retry(2) {
                    sh "cd ${APP_DIR} && sudo php -dmemory_limit=750M /usr/local/bin/composer update --no-scripts --prefer-dist"
                }
            }
        }
        stage('Test') {
            steps {
                sh "${APP_DIR}/vendor/bin/phpunit -c ${APP_DIR}/phpunit.xml"
            }
        }
        stage('Deploy') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'deploy-app', usernameVariable: 'FUSER', passwordVariable: 'FPWD')]) {
                    echo 'git ftp push --user $FUSER --passwd $FPWD -f --remote-root / --syncroot ./ --disable-epsv ftp://domain.com -v'
                }
            }
        }
    }
}
