pipeline {
    agent any

    environment {
        DEFAULT_BRANCH = 'tp3'
        BRANCH = 'master'
        COMMIT_ID = ''
        REPO_URL = 'https://github.com/Fichen/utn-devops.git'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*' ]], extensions: [],  url: "${REPO_URL}"])
                script {
                    COMMIT_ID = sh(returnStdout: true, script: 'git rev-parse HEAD').trim()
                    BRANCH = sh(returnStdout: true, script: "git name-rev ${COMMIT_ID} --name-only").trim()
                }
            }
        }
        stage('Build') {
            steps {
                script {
                    sh(returnStdout: true, script: 'npm run build')
                }
            }
        }
        stage('Running Unit Tests') {
            steps {
                script {
                    sh(returnStdout: true, script: 'npm run test -- --silent')
                }
            }
        }
        stage('Deploy to Develop') {
            when { branch "${DEFAULT_BRANCH}" }
            steps {
                echo 'Deploying to Develop'
                script {
                    echo "branch $DEFAULT_BRANCH"
                    echo "COMMIT $COMMIT_ID"
                    echo "sh script/deploy_script"
                    echo 'Deployment to develop end'
                }
            }
        }
        stage('Deploy to Stage') {
            when { branch 'RC-*' }
            steps {
                echo "Deploying to stage, branch ${BRANCH_NAME}"
                script {
                    echo "branch $DEFAULT_BRANCH"
                    echo "COMMIT $COMMIT_ID"
                    echo "sh script/deploy_script stage"
                    echo 'Deployment to stage end'
                }
            }
        }
    }
}